import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { twMerge } from "tailwind-merge";

import Header from "@/components/Header/header";
import Footer from "@/components/Footer/footer";
import { ClientContexts } from "@/contexts/ClientContexts";
import { getCartFromCookie } from "@/actions/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartFromDatabase = await getCartFromCookie();
  return (
    <html lang="en">
      <body
        className={twMerge(
          `${inter.className} container mx-auto min-h-screen items-center flex flex-col w-full`
        )}
      >
        <ClientContexts cartFromDatabase={cartFromDatabase}>
          <Header />
          {children}
          <Footer />
        </ClientContexts>
      </body>
    </html>
  );
}
